'use client';
// quiz client component
// receives quiz questions from page.tsx as props & manages
// current question, chosen answer, score, streak, logging results

import { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import { SignInButton } from '@clerk/nextjs';
import type { Prisma } from '@prisma/client';

// fetch TS types generated by Prisma schema
// in this case, get 10 generated Questions each with 4 nested Answers
type QuestionWithAnswers = Prisma.QuestionGetPayload<{
	include: { answers: true };
}>;

type Phase = 'quiz' | 'results';

interface Props {
	questions: QuestionWithAnswers[];
	isGuest?: boolean;
}

// create tailwind presets
const ANSWER_CLASSES = {
	default:
		'border-ow-blue/50 bg-ow-blue/10 hover:bg-ow-light-blue/10 hover:border-ow-light-blue/45 cursor-pointer',
	selected: 'border-ow-orange/80 bg-ow-orange/15 cursor-pointer',
	correct: 'border-green-500/70 bg-green-500/10 cursor-default',
	wrong: 'border-red-500/70 bg-red-500/10 cursor-default',
	neutral: 'border-ow-blue/20 bg-ow-blue/5 opacity-40 cursor-default',
} as const;

const LETTER_CLASSES = {
	default:
		'bg-ow-blue/40 text-white/45 group-hover:bg-ow-light-blue/20 group-hover:text-ow-light-blue',
	selected: 'bg-ow-orange/30 text-ow-orange',
	correct: 'bg-green-500/25 text-green-400',
	wrong: 'bg-red-500/25 text-red-400',
	neutral: 'bg-ow-blue/20 text-white/25',
} as const;

const LETTERS = ['A', 'B', 'C', 'D'] as const;

// HELPERS
// consider moving some to /lib/utils

// Lowercase all caps Category from Prisma schema
const lowercaseCategory = (category: string): string =>
	category
		.replace(/_/g, ' ')
		.toLowerCase()
		.replace(/\b\w/g, (char) => char.toUpperCase());

// Display results screen message
// consider implementing more complex elo system
const getResultMessage = (score: number, total: number): string => {
	const pct = score / total;
	if (pct === 1) return 'SEXTUPLE KILL';
	if (pct >= 0.7) return 'UPHILL BATTLE';
	if (pct >= 0.4) return 'VICTORY';
	return 'DEFEAT';
};

const QuizClient = ({ questions, isGuest = false }: Props) => {
	const router = useRouter();
	const [phase, setPhase] = useState<Phase>('quiz'); // are we in quiz or results phase?
	const [currIndex, setCurrIndex] = useState(0); // 0-based index to determine current question
	const [selectedIndex, setSelectedIndex] = useState<number | null>(null); // 0-based index or null determines currently selected answer for this question
	const [hasAnswered, setHasAnswered] = useState(false); // lock in selected answer
	const [score, setScore] = useState(0); // total correct, from 0-10
	const [streak, setStreak] = useState(0); // current consecutive streak
	const [maxStreak, setMaxStreak] = useState(0); // max total streak
	const [selectedAnswers, setSelectedAnswers] = useState<number[]>([]); //save record of answers given

	const question = questions[currIndex];
	const total = questions.length; // tentatively will always be 10
	const progressPercent = ((currIndex + 1) / total) * 100;

	const handleSelectAnswer = (index: number) => {
		// handle score after answer submission
		if (hasAnswered) return;
		setSelectedIndex(index);
		setHasAnswered(true);
		setSelectedAnswers(prev => [...prev, index]);

		const isCorrect = question.answers[index].isCorrect;

		if (isCorrect) {
			// increment score & streak, & set max streak
			setScore((s) => s + 1);
			const newStreak = streak + 1;
			setStreak(newStreak);

			setMaxStreak((ms) => Math.max(ms, newStreak));
		} else {
			setStreak(0);
		}
	};
	const handleNext = async () => {
		// handle advancing to next question or changing to results phase
		if (currIndex < total - 1) {
			setCurrIndex((i) => i + 1);
			setSelectedIndex(null);
			setHasAnswered(false);
		} else {
			if (!isGuest) {
				await fetch('/api/quiz/attempt', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({
						score,
						//send additional info about the question to DB, useful for achievements
						answers: questions.map((q, i) => ({
							questionId: q.id,
							answerId: q.answers[selectedAnswers[i]].id,
							isCorrect: q.answers[selectedAnswers[i]].isCorrect,
						}))
						}),
				});
			}
			setPhase('results');
		}
	};
	const handleRequeue = () => {
		// reset all state and re-run the server component to get fresh questions
		setCurrIndex(0);
		setSelectedIndex(null);
		setHasAnswered(false);
		setScore(0);
		setStreak(0);
		setMaxStreak(0);
		setPhase('quiz');
		setSelectedAnswers([]);
		router.refresh();
	};

	// use our tailwind presets
	const getAnswerClass = (index: number): string => {
		// highlight selected answer orange; else blue
		if (!hasAnswered) {
			return selectedIndex === index
				? ANSWER_CLASSES.selected
				: ANSWER_CLASSES.default;
		}
		// after submitting, highlight correct in green, wrong in red, else dim
		if (question.answers[index].isCorrect) return ANSWER_CLASSES.correct;
		if (selectedIndex === index) return ANSWER_CLASSES.wrong;
		return ANSWER_CLASSES.neutral;
	};
	const getLetterClass = (index: number): string => {
		if (!hasAnswered) {
			return selectedIndex === index
				? LETTER_CLASSES.selected
				: LETTER_CLASSES.default;
		}
		if (question.answers[index].isCorrect) return LETTER_CLASSES.correct;
		if (selectedIndex === index) return LETTER_CLASSES.wrong;
		return LETTER_CLASSES.neutral;
	};

	// RESULTS PHASE
	if (phase === 'results') {
		const pct = Math.round((score / total) * 100);
		const message = getResultMessage(score, total);

		return (
			<div className="flex-1 flex flex-col items-center justify-center bg-ow-dark-blue p-6 gap-8">
				<div className="text-center">
					<p className="text-ow-orange text-[11px] font-medium tracking-[0.28em] uppercase mb-3">
						{isGuest ? 'Guest Quiz Complete' : 'Quiz Complete'}
					</p>
					{/*score currently calced as correct / total */}
					<h1 className="text-white font-black text-6xl uppercase tracking-tight mb-2">
						{score} <span className="text-white/30">/ {total}</span>
					</h1>

					<p className="text-white/50 text-sm uppercase tracking-wisdest mt-1">
						{pct}% correct: {message}
					</p>

					{/*acknowledge streaks 3 or more*/}
					{maxStreak >= 3 && (
						<p className="text-ow-orange/70 text-xs tracking-widest uppercase mt-2">
							Best streak: {maxStreak}!
						</p>
					)}
				</div>

				<div className="flex flex-col items-center gap-3 w-full max-w-sm">
					{isGuest && (
						<SignInButton mode="modal">
							<button className="w-full bg-ow-orange text-white py-3 rounded font-black uppercase text-sm tracking-widest hover:bg-orange-600 transition-colors">
								Sign In to Save Your Score
							</button>
						</SignInButton>
					)}
					<button
						onClick={handleRequeue}
						className={`w-full py-3 rounded font-black uppercase text-sm tracking-widest transition-colors cursor-pointer ${
							isGuest
								? 'border border-white/20 text-white/60 hover:text-white hover:border-white/40'
								: 'bg-ow-orange text-ow-dark-blue hover:bg-ow-orange/80'
						}`}
					>
						{isGuest ? 'Play Again' : 'Requeue'}
					</button>
					<Link
						href={isGuest ? '/' : '/quiz'}
						className="text-white/30 text-xs tracking-wider hover:text-white/60 transition-colors uppercase mt-1 flex items-center justify-center gap-2"
					>
						<ArrowLeft size={16} />
						{isGuest ? 'Back to Home' : 'Continue'}
					</Link>
				</div>
			</div>
		);
	}

	// QUIZ PHASE
	return (
		<div className="flex-1 flex flex-col bg-ow-dark-blue p-6 gap-5">
			{/*HEADER*/}
			<div className="flex items-center justify-between">
				<span className="text-white/40 text-[11px] font-medium tracking-[0.22em] uppercase">
					Question {currIndex + 1} / {total}
				</span>
				<span className="text-ow-orange text-[11px] font-semibold tracking-[0.22em] uppercase">
					Score: {score}
				</span>
			</div>

			{/*PROGRESS BAR*/}
			<div className="h-0.5 bg-white/[0.07] rounded-full">
				<div
					className="h-full bg-ow-orange rounded-full transition-all duration-500"
					style={{ width: `${progressPercent}%` }}
				/>
			</div>

			{/*QUESTIONS*/}
			<div className="flex-1 grid grid-cols-3 gap-6 items-stretch">
				{/* QUESTION*/}
				<div className="col-span-2 flex flex-col gap-3 justify-center">
					{/*CATEGORY*/}
					<p className="text-ow-orange text-[10px] font-medium tracking-[0.28em] uppercase">
						{lowercaseCategory(question.category)}
					</p>
					{/*QUESTION TEXT*/}
					{/*questionText is part of every question */}
					{/*questionContext is only for complex quesitons */}
					<h2 className="text-ow-light-blue italic font-black uppercase leading-tight tracking-wide">
						{question.questionText}
					</h2>
					{question.questionContext && (
						<h1 className="text-white font-black text-3xl uppercase leading-tight tracking-wide">
							{question.questionContext}
						</h1>
					)}

					{/*ANSWER FEEDBACK*/}
					{hasAnswered && selectedIndex !== null && (
						<p
							className={`text-sm font-semibold tracking-wide uppercase ${
								question.answers[selectedIndex].isCorrect
									? 'text-green-400'
									: 'text-red-400'
							}`}
						>
							{question.answers[selectedIndex].isCorrect
								? streak > 1
									? `Correct! ${streak} in a row!`
									: 'Correct!'
								: `Wrong. ${question.answers.find((a) => a.isCorrect)?.answerText}`}
						</p>
					)}
				</div>
				{/*Hero/map image*/}
				<div className="relative rounded-xl overflow-hidden border border-white/[0.09] bg-ow-blue/3- min-h-[170px]">
					{question.imageUrl ? (
						<Image
							src={question.imageUrl}
							alt={question.subjectName ?? 'Question Image'}
							fill
							className="object-cover object-top"
						/>
					) : (
						// place holder
						<p>
							place hodor //TODO: implement placeholder image
							should URL fail
						</p>
					)}
				</div>
			</div>

			{/* ANSWERS */}
			<div className="grid grid-cols-2 gap-3">
				{question.answers.map((answer, index) => (
					<button
						key={answer.id}
						onClick={() => handleSelectAnswer(index)}
						className={`
                            group flex items-center gap-4 p-4 rounded-xl text-left
                            border transition-all duration-200 min-h-[62px]
                            disabled:opacity-100
                            ${getAnswerClass(index)}
                        `}
					>
						{/* display letters */}
						<span
							className={`
                            w-8 h-8 rounded-lg flex-shrink-0
                            flex items-center justify-center
                            text-sm font-bold transition-colors duration-200
                            ${getLetterClass(index)}
                        `}
						>
							{LETTERS[index]}
						</span>
						<span className="text-white/85 text-sm font-medium leading-snug">
							{answer.answerText}
						</span>
					</button>
				))}
			</div>

			{/*NEXT BUTTON */}
			<button
				onClick={handleNext}
				disabled={!hasAnswered}
				className={`
                    flex items-center justify-center gap-2
                    bg-ow-orange text-ow-dark-blue
                    py-3 rounded font-black uppercase text-sm tracking-widest
                    hover:bg-ow-orange/80 transition-colors cursor-pointer
                    ${!hasAnswered && 'invisible'}
                `}
			>
				{currIndex < total - 1 ? 'Next Question' : 'See Results'}
				<ArrowRight size={16} />
			</button>
		</div>
	);
};

export default QuizClient;
