'use client';
// quiz client component
// receives quiz questions from page.tsx as props & manages
// current question, chosen answer, score, streak, logging results

import { useState } from 'react';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { ArrowRight, Flame } from 'lucide-react';
import type { Prisma } from '@prisma/client';
import QuizResults from '@/components/QuizResults';
import AnswerButton from '@/components/AnswerButton';

// fetch TS types generated by Prisma schema
// in this case, get 10 generated Questions each with 4 nested Answers
type QuestionWithAnswers = Prisma.QuestionGetPayload<{
	include: { answers: true };
}>;

type Phase = 'quiz' | 'results';

interface Props {
	questions: QuestionWithAnswers[];
	isGuest?: boolean;
}

// create tailwind presets
const ANSWER_CLASSES = {
	default:
		'border-ow-blue/50 bg-ow-blue/10 hover:bg-ow-light-blue/10 hover:border-ow-light-blue/45 cursor-pointer',
	selected: 'border-ow-orange/80 bg-ow-orange/15 cursor-pointer',
	correct: 'border-green-500/70 bg-green-500/10 cursor-default',
	wrong: 'border-red-500/70 bg-red-500/10 cursor-default',
	neutral: 'border-ow-blue/20 bg-ow-blue/5 opacity-40 cursor-default',
} as const;

const LETTER_CLASSES = {
	default:
		'bg-ow-blue/40 text-white/45 group-hover:bg-ow-light-blue/20 group-hover:text-ow-light-blue',
	selected: 'bg-ow-orange/30 text-ow-orange',
	correct: 'bg-green-500/25 text-green-400',
	wrong: 'bg-red-500/25 text-red-400',
	neutral: 'bg-ow-blue/20 text-white/25',
} as const;

const LETTERS = ['A', 'B', 'C', 'D'] as const;

// HELPERS
// consider moving some to /lib/utils

const DIFFICULTY_POINTS: Record<string, number> = {
	EASY: 1,
	MEDIUM: 2,
	HARD: 3,
};

const DIFFICULTY_STYLES: Record<string, string> = {
	EASY: 'text-green-400 border border-green-400/40 bg-green-400/10',
	MEDIUM: 'text-amber-400 border border-amber-400/40 bg-amber-400/10',
	HARD: 'text-red-400 border border-red-400/40 bg-red-400/10',
};

// streak adds a flat bonus on top of difficulty base points
const getStreakBonus = (currentStreak: number): number => {
	if (currentStreak >= 5) return 2;
	if (currentStreak >= 3) return 1;
	return 0;
};

// Lowercase all caps Category from Prisma schema
const lowercaseCategory = (category: string): string =>
	category
		.replace(/_/g, ' ')
		.toLowerCase()
		.replace(/\b\w/g, (char) => char.toUpperCase());


const QuizClient = ({ questions, isGuest = false }: Props) => {
	const router = useRouter();
	const [phase, setPhase] = useState<Phase>('quiz'); // are we in quiz or results phase?
	const [currIndex, setCurrIndex] = useState(0); // 0-based index to determine current question
	const [selectedIndex, setSelectedIndex] = useState<number | null>(null); // 0-based index or null determines currently selected answer for this question
	const [hasAnswered, setHasAnswered] = useState(false); // lock in selected answer
	const [isSubmitting, setIsSubmitting] = useState(false);
	const [score, setScore] = useState(0); // streak-weighted point total
	const [correctCount, setCorrectCount] = useState(0); // raw correct answers, 0-10
	const [streak, setStreak] = useState(0); // current consecutive streak
	const [maxStreak, setMaxStreak] = useState(0); // max total streak
	const [selectedAnswers, setSelectedAnswers] = useState<number[]>([]); //save record of answers given

	const question = questions[currIndex];
	const total = questions.length; // tentatively will always be 10
	const progressPercent = ((currIndex + 1) / total) * 100;

	const handleSelectAnswer = (index: number) => {
		// handle score after answer submission
		if (hasAnswered) return;
		setSelectedIndex(index);
		setHasAnswered(true);
		setSelectedAnswers((prev) => [...prev, index]);

		const isCorrect = question.answers[index].isCorrect;

		if (isCorrect) {
			const newStreak = streak + 1;
			setStreak(newStreak);
			setMaxStreak((ms) => Math.max(ms, newStreak));
			const pts = (DIFFICULTY_POINTS[question.difficulty] ?? 1) + getStreakBonus(newStreak);
			setScore((s) => s + pts);
			setCorrectCount((c) => c + 1);
		} else {
			setStreak(0);
		}
	};
	const handleNext = async () => {
		// handle advancing to next question or changing to results phase
		if (currIndex < total - 1) {
			setCurrIndex((i) => i + 1);
			setSelectedIndex(null);
			setHasAnswered(false);
		} else {
			if (!isGuest) {
				setIsSubmitting(true);
				await fetch('/api/quiz/attempt', {
					method: 'POST',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify({
						score,
						//send additional info about the question to DB, useful for achievements
						answers: questions.map((q, i) => ({
							questionId: q.id,
							answerId: q.answers[selectedAnswers[i]].id,
							isCorrect: q.answers[selectedAnswers[i]].isCorrect,
						})),
					}),
				});
			}
			setPhase('results');
		}
	};
	const handleRequeue = () => {
		// reset all state and re-run the server component to get fresh questions
		setCurrIndex(0);
		setSelectedIndex(null);
		setHasAnswered(false);
		setScore(0);
		setCorrectCount(0);
		setStreak(0);
		setMaxStreak(0);
		setPhase('quiz');
		setSelectedAnswers([]);
		router.refresh();
	};

	// use our tailwind presets
	const getAnswerClass = (index: number): string => {
		// highlight selected answer orange; else blue
		if (!hasAnswered) {
			return selectedIndex === index
				? ANSWER_CLASSES.selected
				: ANSWER_CLASSES.default;
		}
		// after submitting, highlight correct in green, wrong in red, else dim
		if (question.answers[index].isCorrect) return ANSWER_CLASSES.correct;
		if (selectedIndex === index) return ANSWER_CLASSES.wrong;
		return ANSWER_CLASSES.neutral;
	};
	const getLetterClass = (index: number): string => {
		if (!hasAnswered) {
			return selectedIndex === index
				? LETTER_CLASSES.selected
				: LETTER_CLASSES.default;
		}
		if (question.answers[index].isCorrect) return LETTER_CLASSES.correct;
		if (selectedIndex === index) return LETTER_CLASSES.wrong;
		return LETTER_CLASSES.neutral;
	};

	// RESULTS PHASE
	if (phase === 'results') {
		return (
			<QuizResults
				score={score}
				correctCount={correctCount}
				total={total}
				maxStreak={maxStreak}
				isGuest={isGuest}
				onRequeue={handleRequeue}
			/>
		);
	}

	// QUIZ PHASE
	return (
		<div className="flex-1 flex flex-col bg-ow-dark-blue p-6 gap-5">
			{/*HEADER*/}
			<div className="flex items-center justify-between">
				<span className="text-white/40 text-[11px] font-medium tracking-[0.22em] uppercase">
					Question {currIndex + 1} / {total}
				</span>
				<span className="flex items-center gap-1.5 text-ow-orange text-[11px] font-semibold tracking-[0.22em] uppercase">
					{streak >= 3 && (
						<Flame size={13} className="text-ow-orange" />
					)}
					{score} pts
				</span>
			</div>

			{/*PROGRESS BAR*/}
			<div className="h-0.5 bg-white/[0.07] rounded-full">
				<div
					className="h-full bg-ow-orange rounded-full transition-all duration-500"
					style={{ width: `${progressPercent}%` }}
				/>
			</div>

			{/*QUESTIONS*/}
			<div className="flex-1 grid grid-cols-3 gap-6 items-stretch">
				{/* QUESTION*/}
				<div className="col-span-2 flex flex-col gap-3 justify-center">
					{/*CATEGORY + DIFFICULTY*/}
					<div className="flex items-center gap-2">
						<p className="text-ow-orange text-[10px] font-medium tracking-[0.28em] uppercase">
							{lowercaseCategory(question.category)}
						</p>
						<span className={`text-[9px] font-bold tracking-[0.2em] uppercase px-1.5 py-0.5 rounded ${DIFFICULTY_STYLES[question.difficulty] ?? DIFFICULTY_STYLES.EASY}`}>
							{question.difficulty}
						</span>
					</div>
					{/*QUESTION TEXT*/}
					{/*questionText is part of every question */}
					{/*questionContext is only for complex quesitons */}
					<h2 className="text-ow-light-blue italic font-black uppercase leading-tight tracking-wide">
						{question.questionText}
					</h2>
					{question.questionContext && (
						<h1 className="text-white font-black text-3xl uppercase leading-tight tracking-wide">
							{question.questionContext}
						</h1>
					)}

					{/*ANSWER FEEDBACK*/}
					{hasAnswered && selectedIndex !== null && (
						question.answers[selectedIndex].isCorrect ? (
							<div className="flex items-center gap-2 flex-wrap">
								<span className={`text-[10px] font-bold uppercase tracking-widest px-2 py-1 rounded ${DIFFICULTY_STYLES[question.difficulty] ?? DIFFICULTY_STYLES.EASY}`}>
									{question.difficulty} +{DIFFICULTY_POINTS[question.difficulty] ?? 1}
								</span>
								{getStreakBonus(streak) > 0 && (
									<span className="text-[10px] font-bold uppercase tracking-widest px-2 py-1 rounded text-ow-orange border border-ow-orange/40 bg-ow-orange/10">
										Streak +{getStreakBonus(streak)}
									</span>
								)}
								<span className="text-sm font-black text-green-400 uppercase tracking-wide">
									= +{(DIFFICULTY_POINTS[question.difficulty] ?? 1) + getStreakBonus(streak)} pts{streak > 1 ? ` · ${streak} in a row!` : ''}
								</span>
							</div>
						) : (
							<p className="text-sm font-semibold tracking-wide uppercase text-red-400">
								Wrong. {question.answers.find((a) => a.isCorrect)?.answerText}
							</p>
						)
					)}
				</div>
				{/*Hero/map image*/}
				<div className="relative rounded-xl overflow-hidden border border-white/[0.09] bg-ow-blue/3- min-h-[170px]">
					{question.imageUrl ? (
						<Image
							src={question.imageUrl}
							alt={question.subjectName ?? 'Question Image'}
							fill
							className="object-cover object-top"
						/>
					) : (
						// place holder
						<p>
							place hodor //TODO: implement placeholder image
							should URL fail
						</p>
					)}
				</div>
			</div>

			{/* ANSWERS */}
			<div className="grid grid-cols-2 gap-3">
				{question.answers.map((answer, index) => (
					<AnswerButton
						key={answer.id}
						answerText={answer.answerText}
						letter={LETTERS[index]}
						answerClass={getAnswerClass(index)}
						letterClass={getLetterClass(index)}
						onClick={() => handleSelectAnswer(index)}
					/>
				))}
			</div>

			{/*NEXT BUTTON */}
			<button
				onClick={handleNext}
				disabled={!hasAnswered || isSubmitting}
				className={`
                    flex items-center justify-center gap-2
                    bg-ow-orange text-ow-dark-blue
                    py-3 rounded font-black uppercase text-sm tracking-widest
                    hover:bg-ow-orange/80 transition-colors cursor-pointer
                    ${!hasAnswered && 'invisible'}
                `}
			>
				{currIndex < total - 1 ? 'Next Question' : 'See Results'}
				<ArrowRight size={16} />
			</button>
		</div>
	);
};

export default QuizClient;
